### ISSUE TITLE
Install "Derek" Github automation (via Alex Ellis)

### ISSUE THREAD

**Issue by vielmetti** [vielmetti/commonplace#219]
Install the "Derek" Github automation here, as a testbed. Via @alexellis 

- [x] add to .CUSTOMERS file https://github.com/alexellis/derek/issues/152
- [x] add .DEREK.yml file here #219 #220 
- [x] Enable @alexellis as collaborator
- [ ] test integrations

**Comment by vielmetti** [comment]
Follow user guide at https://github.com/alexellis/derek/blob/master/USER_GUIDE.md

Sample .DEREK.yml

```
maintainers:
 - rgee0
 - alexellis
 
features:
 - dco_check
 - comments
 - pr_description_required
 - hacktoberfest
 - release_notes
```

**Comment by vielmetti** [comment]
Done in https://github.com/alexellis/derek/issues/152

**Comment by alexellis** [comment]
Derek doesn't do "help", however you can use `Derek command: value` or `/command: value`. Please see the USER GUIDE for more in the repo.

**Comment by vielmetti** [comment]
Derek set milestone: Infrastructure

**Comment by vielmetti** [comment]
Derek set milestone: Infrastructure
